[project]
name = "lec_knu-techjob"
version = "0.1.0"
description = "Add a short description here"
authors = ["JS HUHH <anarinsk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]

[dependencies]
python = "3.11.5.*"
pandas = "2.1.1.*"
matplotlib = "3.8.0.*"
ipykernel = "6.25.2.*"
jupyter = "1.0.0.*"
seaborn = "0.12.2.*"
